# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_group', '0002_auto_20171022_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='model_pic',
            new_name='picture',
        ),
    ]
