# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_group', '0003_auto_20171022_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='img/items/default.png', upload_to='img/items'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(default='img/persons/user-male-default.png', upload_to='img/persons'),
        ),
    ]
