# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_group', '0004_auto_20171022_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='source',
        ),
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/items'),
        ),
    ]
